embed_assets: on

javascripts:
  workspace:
    - public/javascripts/jquery.js
    - public/javascripts/**.js

stylesheets:
  common:
    - public/stylesheets/application.css
    - public/stylesheets/screen.css

